<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Identity\Shopwave.Modules.Identity.Application\Shopwave.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Catalog\Shopwave.Modules.Catalog.Application\Shopwave.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Inventory\Shopwave.Modules.Inventory.Application\Shopwave.Modules.Inventory.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Orders\Shopwave.Modules.Orders.Application\Shopwave.Modules.Orders.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Payments\Shopwave.Modules.Payments.Application\Shopwave.Modules.Payments.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Stores\Shopwave.Modules.Stores.Application\Shopwave.Modules.Stores.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\Shopwave.Modules.Identity.Infrastructure\Shopwave.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\Shopwave.Shared\Shopwave.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.14" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
