<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shopwave.Modules.Identity.Domain\Shopwave.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shopwave.Shared\Shopwave.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
